/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meet_tensordb_TensorDB */

#ifndef _Included_com_meet_tensordb_TensorDB
#define _Included_com_meet_tensordb_TensorDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meet_tensordb_TensorDB
 * Method:    store
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_meet_tensordb_TensorDB_store
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_meet_tensordb_TensorDB
 * Method:    get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_meet_tensordb_TensorDB_get
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
