/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meet_tensordb_TensorDB */

#ifndef _Included_com_meet_tensordb_TensorDB
#define _Included_com_meet_tensordb_TensorDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meet_tensordb_TensorDB
 * Method:    processTensor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_meet_tensordb_TensorDB_processTensor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
